import type { RehearsalPlan, RehearsalRun, Town } from "../sim/types";
import type { RepoFingerprint } from "../github/fingerprint";

export function runReportMarkdown(input: {
  town: Town;
  plan?: RehearsalPlan | null;
  run: RehearsalRun;
  fingerprint?: RepoFingerprint | null;
}): string {
  const { town, plan, run, fingerprint } = input;
  const r = run.report;
  const lines: string[] = [
    `# Forktown survival report`,
    ``,
    `**Town:** ${town.name}`,
    `**Codebase:** ${town.codebase}`,
    `**Run:** ${run.id}`,
    `**Status:** ${run.status}`,
    `**Verdict:** ${r?.verdict ?? "—"}`,
    ``,
  ];

  if (plan) {
    lines.push(`## Rehearsal`, ``, `- **Title:** ${plan.title}`, `- **Kind:** ${plan.kind}`, `- **Hypothesis:** ${plan.hypothesis}`, `- **Agent:** ${plan.agentName}`, `- **Intensity:** ${plan.intensity}/5`, ``);
  }

  if (fingerprint) {
    lines.push(
      `## Repo fingerprint`,
      ``,
      `- **Source:** ${fingerprint.source ?? "github"}`,
      `- **Files sampled:** ${fingerprint.filesSampled}`,
      `- **Suggested migrations:** ${fingerprint.suggestedMigrations.join(", ")}`,
      `- **Billing / Auth / Migrations:** ${fingerprint.hasBilling} / ${fingerprint.hasAuth} / ${fingerprint.hasMigrations}`,
      ``,
    );
  }

  if (r) {
    lines.push(
      `## Survivability`,
      ``,
      `**Overall:** ${(r.overall * 100).toFixed(1)}%`,
      ``,
      `### Dimensions`,
      ``,
      ...r.dimensions.map((d) => `- **${d.layer}:** ${(d.score * 100).toFixed(0)}% — ${d.note}`),
      ``,
    );

    if (r.nearMiss) {
      lines.push(`> **Near miss:** ${r.nearMiss}`, ``);
    }

    if (r.hypothesis) {
      lines.push(
        `### Hypothesis`,
        ``,
        `- **Status:** ${r.hypothesis.status}`,
        `- **Coverage:** ${(r.hypothesis.coverage * 100).toFixed(0)}%`,
        `- ${r.hypothesis.summary}`,
        r.hypothesis.missing.length ? `- **Missing:** ${r.hypothesis.missing.join(", ")}` : "",
        ``,
      );
    }

    if (r.fidelity != null) {
      lines.push(`**Simulation fidelity:** ${(r.fidelity * 100).toFixed(0)}%`, ``);
    }

    if (r.cast?.length) {
      lines.push(
        `### Decisive cast`,
        ``,
        ...r.cast.map(
          (c) =>
            `- **${c.name}** (${c.role}${c.segment ? `/${c.segment}` : ""}): ${c.topAction} · u=${c.avgUtility} · trust ${(c.finalTrust * 100).toFixed(0)}%`,
        ),
        ``,
      );
    }

    if (r.tippingPoints?.length) {
      lines.push(`### Tipping points`, ``, ...r.tippingPoints.map((t) => `- **${t.kind}:** ${t.summary}`), ``);
    }

    if (r.segments?.length) {
      lines.push(
        `### Segment pulse`,
        ``,
        ...r.segments.map(
          (s) =>
            `- **${s.segment}** (n=${s.count}): trust ${(s.meanTrust * 100).toFixed(0)}% · anger ${(s.meanAnger * 100).toFixed(0)}% · churn-ready ${s.churnReady}`,
        ),
        ``,
      );
    }

    if (r.counterMoves?.length) {
      lines.push(`### Agent counters`, ``, ...r.counterMoves.map((m) => `- ${m}`), ``);
    }

    if (r.scenarioBeats?.length) {
      lines.push(`### Scenario beats`, ``, ...r.scenarioBeats.map((b) => `- **${b.phase}:** ${b.title} — ${b.detail}`), ``);
    }

    if (r.phaseSummaries?.length) {
      lines.push(
        `### Phase trust delta`,
        ``,
        ...r.phaseSummaries.map(
          (p) => `- **${p.phase}:** ${(p.trustDelta * 100).toFixed(0)}% (${p.events} events)`,
        ),
        ``,
      );
    }

    if (r.subjective) {
      lines.push(
        `### Subjective aftermath`,
        ``,
        `- Mean trust: ${(r.subjective.meanTrust * 100).toFixed(0)}%`,
        `- Mean anger: ${(r.subjective.meanAnger * 100).toFixed(0)}%`,
        `- Churn-ready minds: ${r.subjective.churnReady}`,
        ``,
      );
      if (r.subjective.decisiveMoments.length) {
        lines.push(`### Decisive moments`, ``, ...r.subjective.decisiveMoments.map((m) => `- ${m}`), ``);
      }
    }

    if (r.cascadingFailures.length) {
      lines.push(`### Cascading failures`, ``, ...r.cascadingFailures.map((f) => `- ${f}`), ``);
    }

    lines.push(`### Recommendation`, ``, r.recommendation, ``);
    lines.push(`### Agent moves`, ``, ...r.agentActions.map((a) => `- ${a}`), ``);
  }

  lines.push(`---`, `Generated by Forktown · ${new Date().toISOString()}`);
  return lines.join("\n");
}
